/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const GenerationRecord = IDL.Record({
  'id' : IDL.Nat,
  'height' : IDL.Nat,
  'platform' : IDL.Text,
  'imageUrl' : IDL.Text,
  'timestamp' : Timestamp,
  'prompt' : IDL.Text,
  'width' : IDL.Nat,
});

export const idlService = IDL.Service({
  'deleteGenerationRecord' : IDL.Func([IDL.Nat], [], []),
  'getAllGenerationRecords' : IDL.Func(
      [],
      [IDL.Vec(GenerationRecord)],
      ['query'],
    ),
  'saveGenerationRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const GenerationRecord = IDL.Record({
    'id' : IDL.Nat,
    'height' : IDL.Nat,
    'platform' : IDL.Text,
    'imageUrl' : IDL.Text,
    'timestamp' : Timestamp,
    'prompt' : IDL.Text,
    'width' : IDL.Nat,
  });
  
  return IDL.Service({
    'deleteGenerationRecord' : IDL.Func([IDL.Nat], [], []),
    'getAllGenerationRecords' : IDL.Func(
        [],
        [IDL.Vec(GenerationRecord)],
        ['query'],
      ),
    'saveGenerationRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };